import 'dotenv/config'; import express from 'express'; import cors from 'cors'; import mongoose from 'mongoose'; import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken'; import {z} from 'zod'; import {auth,AuthRequest} from './auth'; import {Category,DailyReview,LearningItem,LearningSession,Project,Task,User} from './models';
if(!process.env.JWT_SECRET)throw new Error('JWT_SECRET is required');
const app=express(); app.use(cors()); app.use(express.json({limit:'100kb'}));
const credentials=z.object({username:z.string().trim().min(3).max(40),password:z.string().min(8).max(100)});
app.post('/api/auth/register',async(req,res,next)=>{try{const body=credentials.parse(req.body);const user=await User.create({username:body.username,passwordHash:await bcrypt.hash(body.password,12)});res.status(201).json({token:jwt.sign({},process.env.JWT_SECRET!,{subject:String(user._id),expiresIn:'7d'})})}catch(e){next(e)}});
app.post('/api/auth/login',async(req,res,next)=>{try{const body=credentials.parse(req.body);const user=await User.findOne({username:body.username.trim().toLowerCase()});if(!user||!await bcrypt.compare(body.password,user.passwordHash))return res.status(401).json({error:'Invalid credentials'});res.json({token:jwt.sign({},process.env.JWT_SECRET!,{subject:String(user._id),expiresIn:'7d'})})}catch(e){next(e)}});
const resources:{path:string;model:any}[]=[{path:'projects',model:Project},{path:'categories',model:Category},{path:'tasks',model:Task},{path:'learning',model:LearningItem},{path:'reviews',model:DailyReview}];
for(const {path,model} of resources){app.get(`/api/${path}`,auth,async(req:AuthRequest,res,next)=>{try{res.json(await model.find({userId:req.userId}).sort({createdAt:-1}))}catch(e){next(e)}});app.post(`/api/${path}`,auth,async(req:AuthRequest,res,next)=>{try{res.status(201).json(await model.create({...req.body,userId:req.userId}))}catch(e){next(e)}});app.patch(`/api/${path}/:id`,auth,async(req:AuthRequest,res,next)=>{try{const item=await model.findOneAndUpdate({_id:req.params.id,userId:req.userId},{$set:req.body},{new:true,runValidators:true});if(!item)return res.status(404).json({error:'Not found'});res.json(item)}catch(e){next(e)}});app.delete(`/api/${path}/:id`,auth,async(req:AuthRequest,res,next)=>{try{await model.deleteOne({_id:req.params.id,userId:req.userId});res.status(204).end()}catch(e){next(e)}})}
app.post('/api/learning/:id/sessions',auth,async(req:AuthRequest,res,next)=>{const session=await mongoose.startSession();try{const duration=z.number().positive().parse(req.body.duration);session.startTransaction();const item=await LearningItem.findOne({_id:req.params.id,userId:req.userId}).session(session);if(!item){await session.abortTransaction();return res.status(404).json({error:'Learning item not found'})}const record=await LearningSession.create([{userId:req.userId,learningItemId:item._id,duration,date:req.body.date}],{session});item.completedHours=Math.min(item.totalHours,item.completedHours+duration);item.status=item.completedHours>=item.totalHours?'completed':'in-progress';await item.save({session});await session.commitTransaction();res.status(201).json({session:record[0],item,progress:Math.round(item.completedHours/item.totalHours*100),remainingHours:Math.max(0,item.totalHours-item.completedHours)})}catch(e){await session.abortTransaction();next(e)}finally{session.endSession()}});
app.get('/api/health',(_req,res)=>res.json({status:'ok'}));
app.use((err:any,_req:any,res:any,_next:any)=>{console.error(err);if(err instanceof z.ZodError)return res.status(400).json({error:'Validation failed',details:err.flatten()});if(err?.code===11000)return res.status(409).json({error:'Already exists'});res.status(500).json({error:'Something went wrong'})});
mongoose.connect(process.env.MONGODB_URI||'mongodb://127.0.0.1:27017/lifeos').then(()=>app.listen(process.env.PORT||4000,()=>console.log('LifeOS API ready'))).catch(e=>{console.error(e);process.exit(1)});
