import {Schema,model,models} from 'mongoose';
const owned={userId:{type:Schema.Types.ObjectId,ref:'User',required:true,index:true}};
export const User=models.User||model('User',new Schema({username:{type:String,required:true,unique:true,trim:true,lowercase:true},passwordHash:{type:String,required:true}},{timestamps:true}));
export const Project=models.Project||model('Project',new Schema({...owned,name:{type:String,required:true,trim:true},description:String,status:{type:String,enum:['active','paused','completed'],default:'active'}},{timestamps:true}));
export const Category=models.Category||model('Category',new Schema({...owned,name:{type:String,required:true},color:{type:String,default:'#8b6cff'},description:String},{timestamps:true}));
export const Task=models.Task||model('Task',new Schema({...owned,title:{type:String,required:true},description:String,projectId:{type:Schema.Types.ObjectId,ref:'Project'},categoryId:{type:Schema.Types.ObjectId,ref:'Category'},status:{type:String,enum:['todo','in-progress','done'],default:'todo'},priority:{type:String,enum:['low','medium','high'],default:'medium'}},{timestamps:true}));
export const LearningItem=models.LearningItem||model('LearningItem',new Schema({...owned,title:{type:String,required:true},type:{type:String,enum:['course','book','skill'],required:true},description:String,totalHours:{type:Number,min:0,required:true},completedHours:{type:Number,min:0,default:0},startDate:Date,status:{type:String,enum:['not-started','in-progress','completed'],default:'not-started'}},{timestamps:true,toJSON:{virtuals:true}}));
export const LearningSession=models.LearningSession||model('LearningSession',new Schema({...owned,learningItemId:{type:Schema.Types.ObjectId,ref:'LearningItem',required:true},duration:{type:Number,min:.01,required:true},date:{type:Date,default:Date.now}},{timestamps:true}));
export const DailyReview=models.DailyReview||model('DailyReview',new Schema({...owned,completedTasks:String,learnedToday:String,blockers:String,tomorrowFocus:String,date:{type:Date,default:Date.now}},{timestamps:true}));
